// generate-env.mjs
// Runs before `ng build` to create environment.ts from Vercel env variables.
// Add the corresponding variables in your Vercel project dashboard.

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const content = `// Auto-generated by generate-env.mjs — do not edit manually.
export const environment = {
  production: ${process.env['PRODUCTION'] ?? 'true'},
  apiBaseUrl: '${process.env['API_BASE_URL'] ?? ''}',
  razorpayKeyId: '${process.env['RAZORPAY_KEY_ID'] ?? ''}',
};
`;

const outDir = join(__dirname, 'src', 'environments');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'environment.ts'), content, 'utf-8');

console.log('✅ environment.ts generated successfully.');
